apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostpath: '/mnt/data/mongodb'


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi