apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      type: data
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:latest
        name: mongodb
        env:
        - name: MONGO_INITBD_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        - name: mongodb-config-mount
          mountPath: /config
        - name: mongo-secret-mount
          mountPath: /etc/mongo-credentials
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
        - name: mongodb-secret-mount
          secret:
            secretName: mongodb-secret
        - name: mongodb-config-mount
          configMap: 
            name: mongodb-config
            
        